apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper-pod
spec:
  containers:
    - name: ubuntu-sleeper
      image: ubuntu-sleeper
      imagePullPolicy: Never # Problem - K8S on Docker Desktop pulls images from the remote repository
      command: ["ls"] # replace entry point for docker container
      args: ["."] # replace argument for docker container
      # args: ["10"] # replace argument for docker container